### ISSUE TITLE
New IP Address

### ISSUE THREAD

**Issue by BDFLR** [zhzy0077/mtalk-ips#2]
**_74.125.21.188_**
正在 Ping 74.125.21.188 具有 32 字节的数据:
来自 74.125.21.188 的回复: 字节=32 时间=229ms TTL=97
来自 74.125.21.188 的回复: 字节=32 时间=229ms TTL=97
来自 74.125.21.188 的回复: 字节=32 时间=229ms TTL=96
来自 74.125.21.188 的回复: 字节=32 时间=233ms TTL=97

74.125.21.188 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 229ms，最长 = 233ms，平均 = 230ms

**ChinaTelecom，ChinaMobile** have tested.

**Comment by zhzy0077** [comment]
Added. Thanks
